#ifndef CONFIG_H
#define CONFIG_H

#define APN_NAME "internet"
#define THINGSPEAK_KEY "UROYL2M8FVCGG1ID"
#define SEND_INTERVAL 10000
#define SIM808_RX_PIN 16
#define SIM808_TX_PIN 17
#define MAX_RESPONSE_LEN 256
#define LOG_LVL_ERROR 1
#define LOG_LVL_WARN 2
#define LOG_LVL_INFO 3
#define LOG_LVL_DEBUG 4
#define CURRENT_LOG_LEVEL LOG_LVL_DEBUG

#endif // CONFIG_H
